stages:
  - test
  - report

default:
  image: maven:3.8.2-openjdk-11
  cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .m2/

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_CLI_OPTS: >-
    -DskipTests

test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/allure-results
    expire_in: 1 day

allure-report:
  image: "frankescobar/allure-docker-service:latest"
#  image: "franela/allure-docker:latest"
  stage: report
  script:
    - allure generate --clean target/allure-results -o target/allure-report
  artifacts:
    when: always
    paths:
      - target/allure-report
    expire_in: 1 day