#.production-rules:
#  rules:
#    - if: $CI_COMMIT_BRANCH == "main"

.production-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"

stages:
  - test
  - report

default:
  image: maven:3.6.3-openjdk-11
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .m2/

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_CLI_OPTS: >-
    -DskipTests

test:
  stage: test
  extends: .production-rules
  before_script:
    - |
      apt-get update && apt-get install -y gnupg2
      apt-get update -y & apt-get install -y wget
      DEBIAN_FRONTEND=noninteractive
      apt-get install -y tzdata
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      apt-get update
      apt-get install -y google-chrome-stable
      google-chrome --version

  script:
    - |
      mvn -B dependency:go-offline
      mvn clean
      mvn test

  artifacts:
    when: always
    paths:
      - target/allure-results
    expire_in: 1 day
  allow_failure: true

allure-report:
  image: "frankescobar/allure-docker-service:latest"
  stage: report
  extends: .production-rules
  script:
    - allure generate --clean target/allure-results -o target/allure-report
  artifacts:
    when: always
    paths:
      - target/allure-report
    expire_in: 1 day