services:
  test:
    build: .
    volumes:
      - type: bind
#        source: /home/jenkins/automation-test/allure-json
        source: ~/allure-json
        target: /apps/automation-test/allure-json

#  allure:
#    depends_on:
#      - test
#    image: "frankescobar/allure-docker-service"
#    environment:
#      CHECK_RESULTS_EVERY_SECONDS: 1
#      KEEP_HISTORY: 1
#    ports:
#      - "3000:5050"
#    volumes:
#      - ~/allure-json:/app/allure-results
#
#  allure-ui:
#    depends_on:
#      - allure
#    image: "frankescobar/allure-docker-service-ui"
#    environment:
#      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:3000"
#      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
#    ports:
#      - "2999:5252"
